# Generated by Django 4.2.16 on 2026-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("shortlisted", "Shortlisted"),
                    ("offered", "Offered"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("closed", "Closed"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
