# Generated by Django 4.2.30 on 2026-06-03 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "Onsite"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("base_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("fixed", "Fixed")],
                        default="hourly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("shift_start_time", models.TimeField()),
                ("shift_end_time", models.TimeField()),
                ("slots_available", models.PositiveIntegerField(default=1)),
                ("slots_filled", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("filled", "Filled"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="jobs",
                        to="businesses.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRequiredSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("required", "Required"), ("preferred", "Preferred")],
                        default="required",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_skills",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="jobs_requiring",
                        to="students.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "skill")},
            },
        ),
    ]
