# Generated by Django 4.2.16 on 2026-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="category",
            field=models.CharField(
                choices=[
                    ("cafe_restaurant", "☕ Cafe / Restaurant"),
                    ("retail_shop", "🛍 Retail Shop"),
                    ("office_assistant", "🏢 Office Assistant"),
                    ("event_staffing", "🎪 Event Staffing"),
                    ("delivery_partner", "🚚 Delivery Partner"),
                    ("video_editor", "🎥 Video Editor"),
                    ("graphic_designer", "🎨 Graphic Designer"),
                    ("software_developer", "💻 Software Developer"),
                ],
                default="cafe_restaurant",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="hiring_radius",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=4.0, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_mode",
            field=models.CharField(
                choices=[("onsite", "On-site"), ("remote", "Remote")],
                default="onsite",
                max_length=20,
            ),
        ),
    ]
