# Generated by Django 4.2.30 on 2026-06-03 07:48

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="portfolio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="portfolios/",
                validators=[
                    students.models.validate_file_size,
                    students.models.validate_portfolio_extension,
                ],
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[
                    students.models.validate_file_size,
                    students.models.validate_resume_extension,
                ],
            ),
        ),
    ]
