# Generated by Django 4.2.16 on 2026-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentprofile_portfolio_file_studentprofile_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
