-- SHIFTLY Production-Ready MySQL 8.x Database Schema
-- Generated by Senior Database Architect

CREATE DATABASE IF NOT EXISTS shiftly
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE shiftly;

-- Disable foreign key checks temporarily to drop tables in any order (for clean migrations)
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS verifications;
DROP TABLE IF EXISTS earnings;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS student_badges;
DROP TABLE IF EXISTS skill_badges;
DROP TABLE IF EXISTS ratings_reviews;
DROP TABLE IF EXISTS reputation_logs;
DROP TABLE IF EXISTS chat_messages;
DROP TABLE IF EXISTS chat_participants;
DROP TABLE IF EXISTS chat_rooms;
DROP TABLE IF EXISTS job_applications;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS swipes;
DROP TABLE IF EXISTS job_required_skills;
DROP TABLE IF EXISTS job_postings;
DROP TABLE IF EXISTS student_skills;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS business_profiles;
DROP TABLE IF EXISTS student_profiles;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================================
-- 1. AUTHENTICATION & CORE USER ENTITY
-- =========================================================================

CREATE TABLE users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('student', 'business', 'admin') NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    mfa_secret VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT chk_email_format CHECK (email LIKE '%@%.%')
) ENGINE=InnoDB;

-- =========================================================================
-- 2. PROFILE MODULES
-- =========================================================================

CREATE TABLE student_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    bio TEXT NULL,
    resume_url VARCHAR(255) NULL,
    profile_picture_url VARCHAR(255) NULL,
    reputation_score DECIMAL(5, 2) NOT NULL DEFAULT 100.00,
    hourly_rate_expectation DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    availability_status ENUM('available', 'busy', 'unavailable') NOT NULL DEFAULT 'available',
    latitude DECIMAL(10, 8) NULL,
    longitude DECIMAL(11, 8) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE business_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL UNIQUE,
    company_name VARCHAR(150) NOT NULL,
    company_logo_url VARCHAR(255) NULL,
    website_url VARCHAR(255) NULL,
    description TEXT NULL,
    industry VARCHAR(100) NOT NULL,
    business_registration_no VARCHAR(50) NOT NULL UNIQUE,
    tax_id VARCHAR(50) NULL,
    verification_status ENUM('pending', 'verified', 'rejected') NOT NULL DEFAULT 'pending',
    reputation_score DECIMAL(5, 2) NOT NULL DEFAULT 100.00,
    latitude DECIMAL(10, 8) NULL,
    longitude DECIMAL(11, 8) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_business_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 3. SKILL BADGES SYSTEM
-- =========================================================================

CREATE TABLE skills (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student_skills (
    student_id BIGINT UNSIGNED NOT NULL,
    skill_id BIGINT UNSIGNED NOT NULL,
    level ENUM('beginner', 'intermediate', 'advanced') NOT NULL DEFAULT 'beginner',
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (student_id, skill_id),
    CONSTRAINT fk_studskill_student FOREIGN KEY (student_id) 
        REFERENCES student_profiles (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_studskill_skill FOREIGN KEY (skill_id) 
        REFERENCES skills (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 4. JOB POSTING & SWIPING
-- =========================================================================

CREATE TABLE job_postings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    business_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    work_type ENUM('remote', 'hybrid', 'onsite') NOT NULL DEFAULT 'onsite',
    location_name VARCHAR(255) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    base_pay DECIMAL(10, 2) NOT NULL,
    rate_type ENUM('hourly', 'fixed') NOT NULL DEFAULT 'hourly',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    shift_start_time TIME NOT NULL,
    shift_end_time TIME NOT NULL,
    slots_available INT UNSIGNED NOT NULL DEFAULT 1,
    slots_filled INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('draft', 'active', 'filled', 'archived', 'cancelled') NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_jobs_business FOREIGN KEY (business_id) 
        REFERENCES business_profiles (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_dates CHECK (start_date <= end_date)
) ENGINE=InnoDB;

CREATE TABLE job_required_skills (
    job_id BIGINT UNSIGNED NOT NULL,
    skill_id BIGINT UNSIGNED NOT NULL,
    priority ENUM('required', 'preferred') NOT NULL DEFAULT 'required',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (job_id, skill_id),
    CONSTRAINT fk_jobskill_job FOREIGN KEY (job_id) 
        REFERENCES job_postings (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_jobskill_skill FOREIGN KEY (skill_id) 
        REFERENCES skills (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE swipes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    direction ENUM('like', 'dislike') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_swipes_student FOREIGN KEY (student_id) 
        REFERENCES student_profiles (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_swipes_job FOREIGN KEY (job_id) 
        REFERENCES job_postings (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT uq_student_job_swipe UNIQUE (student_id, job_id)
) ENGINE=InnoDB;

-- =========================================================================
-- 5. MATCHING & APPLICATIONS
-- =========================================================================

CREATE TABLE matches (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    student_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    status ENUM('active', 'unmatched', 'hired') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_matches_student FOREIGN KEY (student_id) 
        REFERENCES student_profiles (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_matches_job FOREIGN KEY (job_id) 
        REFERENCES job_postings (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uq_student_job_match UNIQUE (student_id, job_id)
) ENGINE=InnoDB;

CREATE TABLE job_applications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT UNSIGNED NULL UNIQUE,
    student_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    status ENUM('applied', 'shortlisted', 'offered', 'accepted', 'rejected', 'withdrawn') NOT NULL DEFAULT 'applied',
    cover_letter TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_applications_match FOREIGN KEY (match_id) 
        REFERENCES matches (id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_applications_student FOREIGN KEY (student_id) 
        REFERENCES student_profiles (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_applications_job FOREIGN KEY (job_id) 
        REFERENCES job_postings (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 6. CHAT SYSTEM
-- =========================================================================

CREATE TABLE chat_rooms (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    match_id BIGINT UNSIGNED NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_chatrooms_match FOREIGN KEY (match_id) 
        REFERENCES matches (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE chat_participants (
    chat_room_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (chat_room_id, user_id),
    CONSTRAINT fk_chatparts_room FOREIGN KEY (chat_room_id) 
        REFERENCES chat_rooms (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_chatparts_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE chat_messages (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    chat_room_id BIGINT UNSIGNED NOT NULL,
    sender_id BIGINT UNSIGNED NOT NULL,
    message_type ENUM('text', 'image', 'document') NOT NULL DEFAULT 'text',
    message_content TEXT NOT NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    read_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chatmsgs_room FOREIGN KEY (chat_room_id) 
        REFERENCES chat_rooms (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_chatmsgs_sender FOREIGN KEY (sender_id) 
        REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 7. REPUTATION & RATINGS/REVIEWS
-- =========================================================================

CREATE TABLE reputation_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    points_changed INT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    description VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rep_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE ratings_reviews (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT UNSIGNED NOT NULL,
    reviewer_id BIGINT UNSIGNED NOT NULL,
    reviewee_id BIGINT UNSIGNED NOT NULL,
    rating DECIMAL(2, 1) NOT NULL,
    feedback_text TEXT NULL,
    categories JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_match FOREIGN KEY (match_id) 
        REFERENCES matches (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_reviews_reviewer FOREIGN KEY (reviewer_id) 
        REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_reviews_reviewee FOREIGN KEY (reviewee_id) 
        REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_rating_range CHECK (rating >= 1.0 AND rating <= 5.0)
) ENGINE=InnoDB;

-- =========================================================================
-- 8. BADGE SYSTEM
-- =========================================================================

CREATE TABLE skill_badges (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    icon_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE student_badges (
    student_id BIGINT UNSIGNED NOT NULL,
    badge_id BIGINT UNSIGNED NOT NULL,
    awarded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    awarded_by BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (student_id, badge_id),
    CONSTRAINT fk_studbadges_student FOREIGN KEY (student_id) 
        REFERENCES student_profiles (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_studbadges_badge FOREIGN KEY (badge_id) 
        REFERENCES skill_badges (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_studbadges_admin FOREIGN KEY (awarded_by) 
        REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 9. NOTIFICATIONS MODULE
-- =========================================================================

CREATE TABLE notifications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    type ENUM('match', 'message', 'application_status', 'payment', 'system') NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    payload JSON NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    read_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 10. PAYMENTS / EARNINGS
-- =========================================================================

CREATE TABLE earnings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT UNSIGNED NOT NULL,
    business_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    gross_amount DECIMAL(10, 2) NOT NULL,
    platform_fee DECIMAL(10, 2) NOT NULL,
    net_amount DECIMAL(10, 2) NOT NULL,
    payment_status ENUM('pending', 'escrow', 'released', 'refunded', 'failed') NOT NULL DEFAULT 'pending',
    payout_method VARCHAR(50) NULL,
    transaction_reference VARCHAR(100) NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_earnings_student FOREIGN KEY (student_id) 
        REFERENCES student_profiles (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_earnings_business FOREIGN KEY (business_id) 
        REFERENCES business_profiles (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_earnings_job FOREIGN KEY (job_id) 
        REFERENCES job_postings (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 11. PROFILE VERIFICATION
-- =========================================================================

CREATE TABLE verifications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    document_type ENUM('national_id', 'passport', 'business_license', 'tax_document') NOT NULL,
    document_url VARCHAR(255) NOT NULL,
    status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
    reviewer_id BIGINT UNSIGNED NULL,
    rejection_reason TEXT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_verif_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_verif_reviewer FOREIGN KEY (reviewer_id) 
        REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 12. REPORTING SYSTEM
-- =========================================================================

CREATE TABLE reports (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reporter_id BIGINT UNSIGNED NOT NULL,
    reported_user_id BIGINT UNSIGNED NULL,
    reported_job_id BIGINT UNSIGNED NULL,
    reason_category VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    status ENUM('pending', 'investigating', 'resolved', 'dismissed') NOT NULL DEFAULT 'pending',
    resolver_id BIGINT UNSIGNED NULL,
    resolution_action TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) 
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_reports_reported_user FOREIGN KEY (reported_user_id) 
        REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_reports_reported_job FOREIGN KEY (reported_job_id) 
        REFERENCES job_postings (id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_reports_resolver FOREIGN KEY (resolver_id) 
        REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- 13. ADMIN AUDIT TRAIL
-- =========================================================================

CREATE TABLE audit_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    actor_id BIGINT UNSIGNED NULL,
    action VARCHAR(100) NOT NULL,
    target_table VARCHAR(100) NULL,
    target_id BIGINT UNSIGNED NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    details JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) 
        REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB;

-- =========================================================================
-- INDEX OPTIMIZATIONS
-- =========================================================================

-- Job Discovery Engine
CREATE INDEX idx_jobs_active_search ON job_postings (status, start_date, rate_type, base_pay);

-- Swipe Exclusion and Status Lookup
CREATE INDEX idx_swipes_student_direction ON swipes (student_id, direction);

-- User Notification Fetch Queue
CREATE INDEX idx_notifications_unread ON notifications (user_id, is_read, created_at DESC);

-- Chat Timeline (Optimizing pagination queries)
CREATE INDEX idx_messages_room_timeline ON chat_messages (chat_room_id, created_at DESC);

-- Active Match Checking
CREATE INDEX idx_matches_lookup ON matches (student_id, status);
