# Generated by Django 4.2.30 on 2026-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swipe",
            name="direction",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike"), ("save", "Save")],
                max_length=10,
            ),
        ),
    ]
