# Generated by Django 4.2.30 on 2026-06-03 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("businesses", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="earning",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="earnings",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="earning",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="earnings",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
