# Generated by Django 4.2.16 on 2026-07-09 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("businesses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_businesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="business_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="business_license",
            field=models.FileField(
                blank=True, null=True, upload_to="business_licenses/"
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="gst_document",
            field=models.FileField(blank=True, null=True, upload_to="gst_documents/"),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="gst_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="owner_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="tax_document",
            field=models.FileField(blank=True, null=True, upload_to="tax_documents/"),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="verification_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="verification_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
