# Generated by Django 4.2.16 on 2026-07-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentprofile_portfolio_file_studentprofile_resume"),
        ("businesses", "0002_initial"),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentReputationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation_score", models.IntegerField()),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "punctuality_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "cancellation_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "professional_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("average_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("experience_bonus", models.IntegerField()),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_history",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "punctuality_rate",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "cancellation_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "professional_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("experience_bonus", models.IntegerField(default=0)),
                ("reputation_score", models.IntegerField(default=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessReputationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation_score", models.IntegerField()),
                ("average_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "payment_timeliness_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "job_accuracy_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "cancellation_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "complaint_resolution_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_history",
                        to="businesses.businessprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                (
                    "payment_timeliness_rate",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "job_accuracy_rate",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "cancellation_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "complaint_resolution_rate",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("reputation_score", models.IntegerField(default=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation",
                        to="businesses.businessprofile",
                    ),
                ),
            ],
        ),
    ]
