"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x7v1ym-pv&5dlvx77me3^ur)h=zu6^kv1@h8tr&gxy^gzahawb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third Party Apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "channels",

    # Custom SHIFTLY Apps
    "accounts",
    "students",
    "businesses",
    "jobs",
    "swipes",
    "matches",
    "chat",
    "notifications",
    "ratings",
    "badges",
    "reports",
    "adminpanel",
]

# ASGI Configuration
ASGI_APPLICATION = "config.asgi.application"

# Channel Layers (Using in-memory for testing/local development)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import sys

# Default to SQLite for local development unless explicit MySQL configuration is supplied.
USE_SQLITE = os.environ.get("SHIFTLY_DEV_SQLITE", "True").lower() in ("true", "1", "yes")
MYSQL_CONFIGURED = any(
    os.environ.get(var)
    for var in ("SHIFTLY_DB_HOST", "SHIFTLY_DB_PORT", "SHIFTLY_DB_USER", "SHIFTLY_DB_PASSWORD", "SHIFTLY_DB_NAME")
)

if not USE_SQLITE and MYSQL_CONFIGURED and 'test' not in sys.argv:
    try:
        import pymysql
        mysql_host = os.environ.get("SHIFTLY_DB_HOST", "127.0.0.1")
        mysql_port = int(os.environ.get("SHIFTLY_DB_PORT", "3306"))
        mysql_user = os.environ.get("SHIFTLY_DB_USER", "root")
        mysql_password = os.environ.get("SHIFTLY_DB_PASSWORD", "")
        mysql_db = os.environ.get("SHIFTLY_DB_NAME", "shiftly")

        conn = pymysql.connect(
            host=mysql_host,
            port=mysql_port,
            user=mysql_user,
            password=mysql_password,
            database=mysql_db,
            connect_timeout=1,
        )
        conn.close()
    except Exception as e:
        print(f"[*] WARNING: MySQL database connection failed: {e}")
        print("[*] Falling back to SQLite database for development/testing.")
        USE_SQLITE = True

if 'test' in sys.argv or USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("SHIFTLY_DB_NAME", "shiftly"),
            "USER": os.environ.get("SHIFTLY_DB_USER", "root"),
            "PASSWORD": os.environ.get("SHIFTLY_DB_PASSWORD", ""),
            "HOST": os.environ.get("SHIFTLY_DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("SHIFTLY_DB_PORT", "3306"),
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "charset": "utf8mb4",
            }
        }
    }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Custom User Model definition
AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "login_page"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/assets/"
STATICFILES_DIRS = [
    BASE_DIR / "assets",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# SimpleJWT configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Security setting to allow rendering media documents/PDFs in iframes on the same origin
X_FRAME_OPTIONS = "SAMEORIGIN"

